name: Build Titanium module

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - name: install dependencies
      run: npm install
#     - name: get Titanium SDK version
#       run: |
#         cd android
#         VERSION=`./gradlew -q printSDKName 2>/dev/null |grep TISDK |cut -d':' -f2`
#         echo $VERSION
#       id: get-sdk-version
    - uses: drauggres/setup-titanium@v1
      with:
#        sdk-version: ${{ steps.get-sdk-version.outputs.time }}
        sdk-version: '7.5.1.GA'
    - name: Build with Gradle
      run: |
        cd android
        ./gradlew tiBuild
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: android/dist
